# Bu dosya projeye sponsor olmak isteyenler için bağlantılar içerir
# Detaylı bilgi: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

# GitHub kullanıcı adı
# github: [ibidi]

# Diğer sponsorluk platformları (isteğe bağlı)
# patreon: kullanici_adiniz
# ko_fi: kullanici_adiniz
# buy_me_a_coffee: kullanici_adiniz

# Özel sponsorluk URL'si
custom: ['https://ihsanbakidogan.com']

